version: "3"
services:
  haystack-api:
    container_name: hs-api-container
    build:
      context: .
      dockerfile: Dockerfile
    image: "deepset/haystack-cpu:latest"
    # Mount custom Pipeline YAML and custom Components.
    # volumes:
    #   - ./rest_api/pipeline:/home/user/rest_api/pipeline
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      # See rest_api/pipelines.yaml for configurations of Search & Indexing Pipeline.
      - DOCUMENTSTORE_PARAMS_HOST=es-container
    depends_on:
      - elasticsearch
    networks:
      - es-net
    command: "/bin/bash -c 'sleep 10 && gunicorn rest_api.application:app -b 0.0.0.0 -k uvicorn.workers.UvicornWorker --workers 1 --timeout 180'"

  kibana:
    # This will start an kibana instance (so you have to add your documents yourself)
    #image: "kibana:7.15.2"
    container_name: kb-container
    image: "docker.elastic.co/kibana/kibana:7.15.2"
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch  
    networks:
      - es-net

  elasticsearch:
    # This will start an empty elasticsearch instance (so you have to add your documents yourself)
    #image: "elasticsearch:7.15.2"
    # If you want a demo image instead that is "ready-to-query" with some indexed Game of Thrones articles:
    container_name: es-container
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.2"
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - es-net

  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    image: "deepset/haystack-streamlit-ui:latest"
    ports:
      - 8501:8501
    restart: on-failure
    environment:
      - API_ENDPOINT=http://hs-api-container:8000
      - EVAL_FILE=eval_labels_example.csv
    command: "/bin/bash -c 'sleep 15 && streamlit run webapp.py'"
    networks:
      - es-net

networks:
  es-net:
    driver: bridge
